spring:
  cloud:
    gateway:
      routes:
      - id: learningCenter
        uri: lb://LEARNING-CENTER-SERVICE
        predicates:
        - Path=/api/**
      - id: paymentService
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment/**
