spring:
  cloud:
    gateway:
      routes:
      - id: learningCenter
        uri: lb://LEARNING-CENTER-SERVICE
        path: /api/**
      - id: paymentService
        uri: lb://PAYMENT-SERVICE
        path: /payment/**
