spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
            allowedHeaders:
              - Content-Type
              - Authorization
      routes:
        - id: learning-center-service
          uri: lb://learning-center-service
          predicates:
            - Path=/api/**
        - id: paymentService
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
