spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
            allowedHeaders:
              - Content-Type
              - Authorization
      routes:
        - id: learning-center-service
          uri: lb://learning-center-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1

logback:
  destination:
    url: localhost
    port: 5000
