spring:
  datasource:
    driverClassName: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://${DB_URL}       #lc-postgres:5432/lc-db
    url: jdbc:postgresql://${DB_URL}
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
